FROM golang:1.20-alpine
WORKDIR /app
RUN apk add --no-cache bash
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY pkg ./pkg
COPY main.go .
WORKDIR /app
RUN go build -o /gdcn
EXPOSE 80
ENTRYPOINT [ "/gdcn" ]